build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
        coverage:
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
                        coverage:
                            file: 'coverage.clover'
                            format: 'clover'
filter:
    excluded_paths:
        - 'bin/*'
        - 'tests/*'
        - 'samples/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
                negation: false
            before_parentheses:
                function_declaration: false
                closure_definition: true
