name: Rector

on:
  pull_request:

jobs:
  rector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.13.0

      - name: Install dependencies
        uses: ramsey/composer-install@v1

      - run: composer fix

      - uses: EndBug/add-and-commit@v7.2.1
        with:
          add: .
          message: "Rector Rectify"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
